import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { MainNav } from '@/components/MainNav';
import { Footer } from '@/components/ui/sections/Footer/Footer';
import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin']
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin']
});

export const metadata: Metadata = {
    title: 'Portfolio - Petar Trajanoski',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased dark flex flex-col min-h-screen`}>
                <div className="container mx-auto" aria-hidden="true" />
                <MainNav />
                <div className="flex-1">
                    {children}
                </div>
                <Footer />
            </body>
        </html>
    );
}
